# Numpy

-> Numerical python.

-> Numpy is the core library for scientific computing in python.

-> It provides a high performance multidimensional array object, and tools for working with these arrays.

-> The most basic object in Numpy is the ndarray.

# why numpy?

-> Its convenience & speed.

-> NumPy is much faster than the standard python ways to do computations.

-> We don't have to do the explicit looping and indexing etc. (all of this happens behind the scenes, in precompiled C-code), and thus it is much more concise.

-> NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists

In [1]:
import numpy as np

# creating new numpy array.

In [2]:
var=np.array([1,4,9,16,25,36])     
print(var)

[ 1  4  9 16 25 36]


In [3]:
# to check the type of var
type(var)

numpy.ndarray

In [4]:
# to get the dimension
var.shape

(6,)

In [5]:
# to get the datatypes of array elements
var.dtype

dtype('int32')

# indexing

In [6]:
print(var[1]+var[-1])

40


In [7]:
var2=np.array([[1,2,3,4,5],[1,4,9,16,25]])
print(var2)
print(var2.ndim)
print(var2.shape)
print(var2.dtype)

[[ 1  2  3  4  5]
 [ 1  4  9 16 25]]
2
(2, 5)
int32


In [8]:
print(var2[0,1])

2


In [9]:
print(var2[1,2])

9


# slicing

In [10]:
print(var[1:])

[ 4  9 16 25 36]


In [11]:
print(var[ :4])

[ 1  4  9 16]


In [12]:
print(var2[0, 1:4 ])

[2 3 4]


In [13]:
print(var2[1, 1:4 ])

[ 4  9 16]


# copy vs view

--> copy creates a own copy.

--> view is the just original data.

In [14]:
var3=np.array(["Netzwerk", "Academy", "Banglore", "Reddy", "BDS"])

my_copy=var3.copy()
my_view=var3.view()


(var3[3], var3[4]) = (var3[4], var3[3])

print(my_copy)
print("")
print(my_view)

['Netzwerk' 'Academy' 'Banglore' 'Reddy' 'BDS']

['Netzwerk' 'Academy' 'Banglore' 'BDS' 'Reddy']
