# Numpy2

-> Splitting the arrays

# 1-d

In [1]:
import numpy as np

arr = np.array([0,1,2,3,4,5,6,7,8,9])

newarr = np.array_split(arr,5) # This step helps to split

print(newarr)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [2]:
print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])
print(newarr[4])

[0 1]
[2 3]
[4 5]
[6 7]
[8 9]


# 2-d

In [3]:
import numpy as np

arr = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14]])

newarr = np.array_split(arr,3)

print(newarr)

[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14]])]


In [4]:
import numpy as np

arr = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14]])
print(arr)
print("")
newarr = np.array_split(arr,3,axis=1)
print(newarr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

[array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [12]]), array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14]])]


# Random number

-> It is not a diff.num eachtime, but an unpredicted number logically

In [7]:
# Generate a random number

from numpy import random
die_roll = random.randint(1,7)
print(die_roll)

6


In [9]:
# Generate a random array

# For 1d
x=random.randint(90, size=(7))

print(x)

[87 62  3 79 22 82 67]


In [11]:
# For 2d
x = random.randint(8, size=(2, 3))

print(x)

[[0 5 5]
 [2 3 2]]


# Random permutation

-> An arrangements of elements

Two methods are there:

In [13]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr) # original array will be modified

print(arr)

[4 2 3 5 1]


In [14]:
from numpy import random
import numpy as np

arr = np.array([22,23,24,25,26])

print(random.permutation(arr))
print("")
print(arr)           # won't effect original array

[22 23 25 26 24]

[22 23 24 25 26]
